/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.msi.manning.telephonyexplorer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int callintent_button=0x7f050005;
        public static final int dialintent_button=0x7f050004;
        public static final int gotopnutils_button=0x7f050002;
        public static final int gotosms_button=0x7f050003;
        public static final int gototelmgr_button=0x7f050001;
        public static final int intro_label_main=0x7f050000;
        public static final int intro_label_pn=0x7f050006;
        public static final int intro_label_sms=0x7f05000f;
        public static final int intro_label_telmgr=0x7f050015;
        public static final int label_pninplaceinput=0x7f05000c;
        public static final int label_pninput=0x7f050007;
        public static final int label_pnoutput=0x7f05000a;
        public static final int label_smsinputdest=0x7f050010;
        public static final int label_smsinputtext=0x7f050012;
        public static final int pnformat=0x7f050009;
        public static final int pninplaceinput=0x7f05000d;
        public static final int pninput=0x7f050008;
        public static final int pnnextfocus=0x7f05000e;
        public static final int pnoutput=0x7f05000b;
        public static final int smsinputdest=0x7f050011;
        public static final int smsinputtext=0x7f050013;
        public static final int smssend_button=0x7f050014;
        public static final int telmgroutput=0x7f050016;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int phonenumberutilsexample=0x7f030001;
        public static final int smsexample=0x7f030002;
        public static final int telmgrexample=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
