/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.msi.manning.binder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int add_button=0x7f050006;
        public static final int echo_button=0x7f050008;
        public static final int inputa=0x7f050001;
        public static final int inputb=0x7f050003;
        public static final int labela=0x7f050000;
        public static final int labelb=0x7f050002;
        public static final int labeloutput=0x7f050004;
        public static final int output=0x7f050005;
        public static final int subtract_button=0x7f050007;
    }
    public static final class layout {
        public static final int activity_example=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
